install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install --upgrade -r requirements_build.txt"
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  -
build: off

test_script:
  - "pwd"
  - "ls"
  - ps: tox -r
